### ISSUE TITLE
unit tests are failing on master (f3ca11f)

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt-metadata#98]
I was creating a PR and wanted to run unit tests, but it seems they are currently failing on master (f3ca11f) with:

```
$ go test  ./... 
2020/02/28 19:23:13 Fetching latest manifest...
panic: json: cannot unmarshal object into Go struct field ManifestItems.manual of type [][]*json.RawMessage [recovered]
	panic: json: cannot unmarshal object into Go struct field ManifestItems.manual of type [][]*json.RawMessage

goroutine 31 [running]:
testing.tRunner.func1(0xc00035c200)
	/usr/lib/go-1.11/src/testing/testing.go:792 +0x387
panic(0x9b1800, 0xc000110550)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
github.com/web-platform-tests/wpt-metadata.TestResultsTestPaths.func1(0xc00035c200)
	/home/clopez/webkit/wpt-metadata/test_paths_test.go:50 +0x497
testing.tRunner(0xc00035c200, 0xc00020c7b0)
	/usr/lib/go-1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/go-1.11/src/testing/testing.go:878 +0x35c
FAIL	github.com/web-platform-tests/wpt-metadata	3.129s
```

**Comment by stephenmcgruer** [comment]
Sorry for the inconvenience. This is https://github.com/web-platform-tests/wpt-metadata/issues/80. Part of the work to resolve it has already landed, there is one WIP PR (https://github.com/web-platform-tests/wpt.fyi/pull/1823), and then I think @KyleJu has to do a bit of work once the previous PR has landed.

We hope to get the PR in today.
